# Generated by Django 2.0 on 2020-05-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255, verbose_name='Headline')),
                ('css_class', models.CharField(max_length=255, verbose_name='Css class')),
                ('display', models.CharField(max_length=255, verbose_name='Css class')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Trending',
                'verbose_name_plural': 'Trending',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(upload_to='images/blog', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/product'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='image',
            field=models.ImageField(max_length=255, upload_to='images/promo', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='img',
            field=models.ImageField(upload_to='images/testimonial', verbose_name='Image'),
        ),
    ]
