# Generated by Django 2.0 on 2020-05-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20200530_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='display',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Display'),
        ),
    ]
