# Generated by Django 2.0 on 2020-05-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='background',
            field=models.CharField(default=1, max_length=255, verbose_name='Background'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=2, upload_to='images/category', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Order'),
        ),
    ]
