# Generated by Django 2.0 on 2020-06-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20200530_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtitle')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active?')),
                ('img', models.ImageField(upload_to='images/main-block', verbose_name='Image')),
                ('youtube_video_id', models.CharField(max_length=255, verbose_name='Youtube video id')),
            ],
            options={
                'verbose_name': 'MainBlock',
                'verbose_name_plural': 'MainBlocks',
            },
        ),
        migrations.AddField(
            model_name='promo',
            name='subtitle',
            field=models.CharField(default=1, max_length=255, verbose_name='Subtitle'),
            preserve_default=False,
        ),
    ]
